// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSocketServer.Core.context;

#nullable disable

namespace WebSocketServer.Server.Migrations
{
    [DbContext(typeof(DuckingContext))]
    [Migration("20260210090803_Users and game history")]
    partial class Usersandgamehistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebSocketServer.Core.context.DuckingGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebSocketServer.Core.context.DuckingUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DuckingGameId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DuckingGameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebSocketServer.Core.context.DuckingUser", b =>
                {
                    b.HasOne("WebSocketServer.Core.context.DuckingGame", null)
                        .WithMany("Players")
                        .HasForeignKey("DuckingGameId");
                });

            modelBuilder.Entity("WebSocketServer.Core.context.DuckingGame", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
